version: '3.8'

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turkeybrand
    ports:
      - 8000:8000
    volumes:
      - .:/app
      
  nginx:
    image: nginx:1.21.1
    ports:
      - 80:80
